version: "3"

services:

  aiguillage:
    image: 'soulshake/aiguillage:latest'
    ports:
      - "80:80"
      - "443:443"

  blog:
    build: blog.soulshake.net
    image: ${REGISTRY-127.0.0.1:5000}/blog.soulshake.net:${TAG-latest}
    deploy:
      mode: global
    ports:
    - "80"
    - "443"

  cv:
    build: cv.soulshake.net
    image: ${REGISTRY-127.0.0.1:5000}/cv.soulshake.net:${TAG-latest}
    deploy:
      mode: global
    ports:
    - "80"

  www:
    build: www.soulshake.net
    image: ${REGISTRY-127.0.0.1:5000}/www.soulshake.net:${TAG-latest}
    deploy:
      mode: global
    ports:
    - "80"
    - "443"

# overlay network
