version: "3"

services:

  aiguillage:
    build: aiguillage
    image: ${REGISTRY-127.0.0.1:5000}/aiguillage:${TAG-latest}
    ports:
      - "80:80"
      - "443:443"

  blog:
    build: blog.soulshake.net
    image: ${REGISTRY-127.0.0.1:5000}/blog.soulshake.net:${TAG-latest}
    deploy:
      mode: global
    ports:
    - "80"
    - "443"
    command: bin/hugo
    environment:
      - DEVELOPMENT
      - HUGO_BASEURL


  cv:
    build: cv.soulshake.net
    image: ${REGISTRY-127.0.0.1:5000}/cv.soulshake.net:${TAG-latest}
    deploy:
      mode: global
    ports:
    - "80"
    environment:
      PORT: "80"
    command: /src/bin/wopr


  www:
    build: www.soulshake.net
    image: ${REGISTRY-127.0.0.1:5000}/www.soulshake.net:${TAG-latest}
    deploy:
      mode: global
    ports:
    - "80"
    - "443"
    command: bin/web

# overlay network
